### PR TITLE
Modified logic yo use == instead of is to make sure we dont encounter…

### PR DESCRIPTION
**Pull request by RaviChandraVeeramachaneni**
… warnings

### CODE REVIEW

**Comment by rsokl** [comment]
closes #159

**Comment by RaviChandraVeeramachaneni** [comment]
Thanks Ryan. This is my First Open Source PR and I am very excited.
Thanks for the opportunity. I have some new content ideas and reach you out
soon. Is there any specific email ID that I can use to be in touch with you?


Ravi Chandra Veeramachaneni

**Comment by rsokl** [comment]
@RaviChandraVeeramachaneni it would be best for you to post those ideas in the issue thread on this GitHub repo. This way the other PLYMI contributors/developers can participate in the discussions about ideas / new content.

Best regards,
Ryan

**Comment by RaviChandraVeeramachaneni** [comment]
Thanks Ryan. Will do that. Have some ideas and will do that soon. 


Thanks in Advance

Regards, 
Ravi Chandra Veeramachaneni

**Pull request merged**
